---
title: "Git / GitHub Info"
author: "napoli"
date: "2/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
- 👋 Howdy, I’m @sdkritikos https://twitter.com/metacode


<!---
sdkritikos/sdkritikos is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->

## Basic git

```{r, eval=FALSE}

# make localy a copy of the repository at <url> 
git clone <url>

# edit <file name>
# show changes that were made during editing
git diff

# finished editing ...
# new version of the file that we want to save
git add <file name>
  
# now is the time to actually make the save
git commit -m "message"  

# combine the add and commit steps together
git commit -am "message"   

# status report on the repository
git status

# NEXT 12...
```

## Basic GitHub


### Create a repo

GitHub Docs: [Create a repo: To put your project up on GitHub, you'll need to create a repository for it to live in](https://docs.github.com/en/get-started/quickstart/create-a-repo)

```{r, eval=FALSE}
In the upper-right corner of any page, use the drop-down menu, and select New repository. Type a short, memorable name for your repository. ...

Optionally, add a description of your repository. ...

Choose a repository visibility. ...

Select Initialize this repository with a README.

Click Create repository
```



### How to push a local directory to GitHub

[Adding an existing project to GitHub using the command line](https://docs.github.com/en/get-started/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line)

```{r, eval=FALSE}
Create a new repository on GitHub.com. ...

Open TerminalTerminalGit Bash

Change the current working directory to your local project.

Initialize the local directory as a Git repository. ...
$ git init -b main

Add the files in your new local repository. ...
# Adds the files in the local repository and stages them for commit. To unstage a file, use 'git reset HEAD YOUR-FILE'.
$ git add .


Commit the files that you have staged in your local repository
# Commits the tracked changes and prepares them to be pushed to a remote repository. To remove this commit and modify the file, use 'git reset --soft HEAD~1' and commit and add the file again.
$ git commit -m "First commit"

#### GitHub suggestion
# https://github.com/sdkritikos/test.git 
# was shown after trying to create new repo
git remote add origin https://github.com/sdkritikos/test.git
git branch -M main
git push -u origin main
## new repo checks out

```

## GitHub suggestion on how to puch local 

```{r, eval=FALSE}
…or create a new repository on the command line

echo "# test" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/sdkritikos/test.git
git push -u origin main


…or push an existing repository from the command line

#### THIS was used
git remote add origin https://github.com/sdkritikos/test.git
git branch -M main
git push -u origin main
```










